fix: update getVulnerabilities to match arborist api results
NodeSecure/vulnera pull request #158
Opened 2023-07-02 14:34 UTC by halcin

2023-07-18 20:17 UTC, PierreDemailly approved these changes
lgtm

2023-07-21 09:59 UTC, tony-go requested changes
Thanks for the PR 😍 

But we should add a unit test to cover this. cf https://github.com/NodeSecure/vulnera/tree/main/test/strategies/npm_audit

The error we found should have been caught somehow.

2023-07-21 09:59 UTC, tony-go commented on src/strategies/npm-audit.js
> +    return formatVulnerabilities(VULN_MODE.NPM_AUDIT, Object.values(advisories));
`flatMap`return an Array so we should probably not use `Object.values` here.

```suggestion
    return formatVulnerabilities(VULN_MODE.NPM_AUDIT, advisories);
```

2023-07-22 23:52 UTC, halcin commented
In fact the tests were already failing, I reported the problem. Antoine-coulon had proposed to solve them because it is necessary to rework the integration tests

2023-08-01 16:14 UTC, fraxken approved these changes

2023-09-01 23:17 UTC, merged